# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk8

# создание БД для тестов
services:
  - postgresql
before_install:
  - psql -c "CREATE DATABASE country_information;" -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на moroz.future@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - moroz.future@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="b24a95d8-56e7-40e2-a3dd-f6036138ac83"